// Support matrix: what works on which OS, in the open-source (per-user) and
// enterprise (managed, standalone profile) editions.
//
// One source for /docs/support-matrix, the "Platform support" table on
// /docs/connectors and the <ConnectorSupport> strip on each connector page.
//
// Where each fact comes from:
// - OS allowed at all: internal/gateway/connector/platform_support.go
//   (windowsConnectorSupport; every connector is supported on Linux and macOS).
// - Minimum agent version: cli/defenseclaw/inventory/hook_contracts.json
//   (lowest min_inclusive, or the exact builds); Kiro's standalone floors are in
//   internal/enterprisehooks/agent_floor_standalone.go.
// - Block, native ask and fail closed: data/capability-matrix.json (imported,
//   never copied, so the two pages can't drift).
// - Enterprise route: internal/enterprisepolicy/types.go RouteFor.
// - Statuses: the GENERATED block below, written by the out-of-repo
//   site-matrix/gen.py from the live-test ledger. A cell is "supported" only
//   when the code allows it and a live test verified it in this release.
//
// OpenClaw and ZeptoClaw (proxy mode) and the Copilot VS Code extension are
// intentionally not in this file. Their own pages describe them.

import capability from '@/data/capability-matrix.json';

export type OsId = 'linux' | 'macos' | 'windows';
export type Edition = 'oss' | 'enterprise';
// supported   = verified live in this release on that OS (and allowed by the code)
// preview     = allowed by the code, not verified live in this release
// unsupported = the code refuses it on that OS or in that edition
// not-offered = the edition doesn't include it
export type Status = 'supported' | 'preview' | 'unsupported' | 'not-offered';
export type Route = 'machine policy' | 'per-user' | 'unsupported';
export type Integration = 'Native hooks' | 'Plugin' | 'Policy plugin' | 'Policy API';
export type FeatureGroup = 'Protect' | 'Discover' | 'Observe' | 'Operate' | 'Enterprise controls';

export const OS_IDS: OsId[] = ['linux', 'macos', 'windows'];

// Status strings are one letter per OS in Linux, macOS, Windows order.
// OSS connector cells carry two letters: status, then observability.
interface GeneratedStatus {
  asOf: string;
  oss: Record<string, string>;
  enterprise: Record<string, string>;
  features: Record<string, { oss: string; enterprise: string }>;
}

// BEGIN GENERATED by site-matrix/gen.py from the final-cert ledger. Regenerate, don't hand-edit.
// Codes: S supported (verified live), P preview, U unsupported (refused by code), N not offered.
// Order of each string: Linux, macOS, Windows. OSS connector cells: <status><observability>.
export const generated: GeneratedStatus = {
  asOf: '2026-10-03',
  oss: {
    claudecode: 'SS SS SS',
    codex: 'SS SS SS',
    copilot: 'SS SS SS',
    cursor: 'SS SS SS',
    devin: 'SS SS SS',
    antigravity: 'SS SS SS',
    kiro: 'SS SS SS',
    opencode: 'SS SS SS',
    amp: 'SS SS SS',
    hermes: 'SS SS SS',
    openhands: 'SS SS UU',
    omnigent: 'SS SS PP',
  },
  enterprise: {
    claudecode: 'SSS',
    codex: 'SSS',
    copilot: 'SSS',
    cursor: 'SPS',
    devin: 'SSS',
    antigravity: 'SSS',
    kiro: 'PPS',
    opencode: 'SSS',
    amp: 'SSS',
    hermes: 'SSS',
    openhands: 'SSU',
    omnigent: 'PPU',
  },
  features: {
    guardrails: { oss: 'SSS', enterprise: 'SSS' },
    policy: { oss: 'SSS', enterprise: 'SSS' },
    codeguard: { oss: 'SSS', enterprise: 'PPP' },
    'skill-scanner': { oss: 'SSP', enterprise: 'SSP' },
    'mcp-scanner': { oss: 'SPS', enterprise: 'SSP' },
    judge: { oss: 'SSP', enterprise: 'PPP' },
    redaction: { oss: 'SSP', enterprise: 'NNN' },
    sandboxes: { oss: 'PPU', enterprise: 'UUU' },
    acp: { oss: 'PSP', enterprise: 'PPP' },
    'ai-discovery': { oss: 'SSS', enterprise: 'SSP' },
    'runtime-discovery': { oss: 'SSS', enterprise: 'SSP' },
    tools: { oss: 'SSS', enterprise: 'NNN' },
    plugins: { oss: 'PSS', enterprise: 'NNN' },
    registries: { oss: 'PSS', enterprise: 'NNN' },
    aibom: { oss: 'SPP', enterprise: 'NNN' },
    otlp: { oss: 'SSS', enterprise: 'SSS' },
    galileo: { oss: 'SSS', enterprise: 'SSS' },
    splunk: { oss: 'PPP', enterprise: 'PPP' },
    'local-stack': { oss: 'SSP', enterprise: 'NNN' },
    alerts: { oss: 'SSS', enterprise: 'NNN' },
    webhooks: { oss: 'SSS', enterprise: 'PPP' },
    audit: { oss: 'SSP', enterprise: 'PPP' },
    install: { oss: 'SSS', enterprise: 'SSS' },
    upgrade: { oss: 'SSS', enterprise: 'SSS' },
    uninstall: { oss: 'SSS', enterprise: 'SSS' },
    health: { oss: 'SSS', enterprise: 'SSS' },
    keys: { oss: 'SSS', enterprise: 'PPP' },
    tui: { oss: 'SSS', enterprise: 'NNN' },
    'macos-app': { oss: 'NPN', enterprise: 'NNN' },
    'machine-policy': { oss: 'NNN', enterprise: 'SSS' },
    tamper: { oss: 'NNN', enterprise: 'SSS' },
    enrollment: { oss: 'NNN', enterprise: 'SSS' },
    'foreign-hook-guard': { oss: 'NNN', enterprise: 'SSP' },
    mdm: { oss: 'NNN', enterprise: 'SSS' },
  },
};
// END GENERATED

const CODE: Record<string, Status> = {
  S: 'supported',
  P: 'preview',
  U: 'unsupported',
  N: 'not-offered',
};

function decode(code: string | undefined, where: string): Status {
  const status = code ? CODE[code] : undefined;
  if (!status) throw new Error(`support-matrix: bad status code ${JSON.stringify(code)} for ${where}`);
  return status;
}

function perOs(codes: string, where: string): Record<OsId, Status> {
  const letters = codes.replace(/\s+/g, '');
  if (letters.length !== 3) throw new Error(`support-matrix: ${where} needs 3 status letters, got ${codes}`);
  return {
    linux: decode(letters[0], `${where} linux`),
    macos: decode(letters[1], `${where} macos`),
    windows: decode(letters[2], `${where} windows`),
  };
}

// ---------------------------------------------------------------------------
// Platforms

export interface Platform {
  label: string;
  arch: string;
  certifiedOn: string;
  enterpriseCertifiedOn: string;
}

export const platforms: Record<OsId, Platform> = {
  linux: {
    label: 'Linux',
    arch: 'x86_64, arm64',
    certifiedOn: 'RHEL',
    enterpriseCertifiedOn: 'RHEL (.rpm). The .deb is built but not certified in this release',
  },
  macos: {
    label: 'macOS',
    arch: 'Apple silicon',
    certifiedOn: 'macOS on Apple silicon',
    enterpriseCertifiedOn: 'macOS on Apple silicon (.pkg)',
  },
  windows: {
    label: 'Windows',
    arch: 'x64',
    certifiedOn: 'Windows x64',
    enterpriseCertifiedOn: 'Windows x64 (Setup.exe)',
  },
};

// ---------------------------------------------------------------------------
// Connectors

interface CapabilityConnector {
  id: string;
  label: string;
  hooks: { canBlock: boolean; canAskNative: boolean; supportsFailClosed: boolean };
}

const capabilityById = new Map(
  (capability.connectors as CapabilityConnector[]).map((connector) => [connector.id, connector]),
);

interface ConnectorSource {
  id: string;
  integration: Integration;
  minVersion: string;
  versionNote?: string;
  notes?: Partial<Record<OsId, string>>;
  route: Record<OsId, Route>;
  routeNote?: string;
}

const MACHINE: Record<OsId, Route> = { linux: 'machine policy', macos: 'machine policy', windows: 'machine policy' };
const PER_USER: Record<OsId, Route> = { linux: 'per-user', macos: 'per-user', windows: 'per-user' };
const PER_USER_NO_WINDOWS: Record<OsId, Route> = { linux: 'per-user', macos: 'per-user', windows: 'unsupported' };

// Order: adoption, as on the connectors index and in the docs nav.
const connectorSources: ConnectorSource[] = [
  {
    id: 'claudecode',
    integration: 'Native hooks',
    minVersion: '2.1.154',
    notes: { windows: 'Native executable hooks. WSL is outside the native contract.' },
    route: MACHINE,
  },
  {
    id: 'codex',
    integration: 'Native hooks',
    minVersion: '0.124.0',
    notes: { windows: 'System PowerShell bridge to the packaged hook executable.' },
    route: MACHINE,
  },
  {
    id: 'copilot',
    integration: 'Native hooks',
    minVersion: '1.0.18',
    notes: { windows: "Uses Copilot CLI's PowerShell hook field." },
    route: MACHINE,
  },
  {
    id: 'cursor',
    integration: 'Native hooks',
    minVersion: '2.4.0',
    versionNote: 'Cursor Agent 2.4.0 up to 4.0.0, and Agent build 2026.07.23-e383d2b.',
    notes: { windows: 'Managed PowerShell adapter.' },
    route: MACHINE,
  },
  {
    id: 'devin',
    integration: 'Native hooks',
    minVersion: '3000.4.25',
    versionNote: 'Exact Devin CLI builds 3000.4.25 and 3000.11.3.',
    notes: { windows: 'Same-user Devin CLI 3000.4.25 through the system PowerShell bridge.' },
    route: PER_USER,
  },
  {
    id: 'antigravity',
    integration: 'Native hooks',
    minVersion: '1.1.8',
    notes: { windows: 'Packaged PowerShell hook launcher.' },
    route: PER_USER,
  },
  {
    id: 'kiro',
    integration: 'Native hooks',
    minVersion: 'Not gated',
    versionNote: 'Per-user installs are not version-gated. The enterprise standalone profile requires kiro-cli 2.24.1 or Kiro IDE 1.0.182.',
    route: PER_USER,
    routeNote: 'Editors that start Kiro over ACP can also use the ACP guard.',
  },
  {
    id: 'opencode',
    integration: 'Plugin',
    minVersion: '1.18.10',
    versionNote: 'Contract covers 1.18.10 up to 1.19.0.',
    route: PER_USER,
    routeNote: 'Machine policy when the managed OpenCode plugin is installed.',
  },
  {
    id: 'amp',
    integration: 'Policy plugin',
    minVersion: '0.0.1785334225',
    notes: { windows: 'Owner-only TypeScript system-policy plugin.' },
    route: PER_USER,
  },
  {
    id: 'hermes',
    integration: 'Native hooks',
    minVersion: '0.19.0',
    versionNote: 'Contract covers 0.19.0 up to 0.22.0.',
    notes: { windows: "Hermes' own terminal tool needs its bundled Git Bash." },
    route: PER_USER,
  },
  {
    id: 'openhands',
    integration: 'Native hooks',
    minVersion: '1.12.0',
    notes: { windows: 'OpenHands CLI needs WSL, and DefenseClaw has no WSL connector path.' },
    route: PER_USER_NO_WINDOWS,
  },
  {
    id: 'omnigent',
    integration: 'Policy API',
    minVersion: '0.7.0',
    versionNote: 'Contract covers 0.7.0 up to 0.14.0.',
    notes: {
      windows: 'Degraded mode: server and SDK policy path only, without terminal wrappers or sandbox parity.',
    },
    route: PER_USER_NO_WINDOWS,
  },
];

export interface ConnectorOsCell {
  status: Status;
  // Pre-execution block on this OS: capability-matrix hooks.canBlock, unless unsupported.
  block: boolean;
  // DefenseClaw telemetry verified reaching an OTLP back end (Grafana) and Galileo.
  observability: Status;
  note?: string;
}

export interface ConnectorRow {
  id: string;
  label: string;
  integration: Integration;
  minVersion: string;
  versionNote?: string;
  canAskNative: boolean;
  supportsFailClosed: boolean;
  oss: Record<OsId, ConnectorOsCell>;
  enterprise: Record<OsId, { route: Route; status: Status }>;
  routeNote?: string;
}

function buildConnector(source: ConnectorSource): ConnectorRow {
  const cap = capabilityById.get(source.id);
  const ossCodes = generated.oss[source.id];
  const entCodes = generated.enterprise[source.id];
  if (!cap || !ossCodes || !entCodes) throw new Error(`support-matrix: missing data for ${source.id}`);
  const pairs = ossCodes.trim().split(/\s+/);
  if (pairs.length !== 3) throw new Error(`support-matrix: ${source.id} needs 3 OSS cells`);
  const entStatus = perOs(entCodes, `${source.id} enterprise`);
  const oss = {} as Record<OsId, ConnectorOsCell>;
  const enterprise = {} as ConnectorRow['enterprise'];
  OS_IDS.forEach((os, i) => {
    const status = decode(pairs[i][0], `${source.id} ${os}`);
    oss[os] = {
      status,
      block: cap.hooks.canBlock && status !== 'unsupported',
      observability: decode(pairs[i][1], `${source.id} ${os} observability`),
      note: source.notes?.[os],
    };
    const route = source.route[os];
    enterprise[os] = { route, status: route === 'unsupported' ? 'unsupported' : entStatus[os] };
  });
  return {
    id: source.id,
    label: cap.label,
    integration: source.integration,
    minVersion: source.minVersion,
    versionNote: source.versionNote,
    canAskNative: cap.hooks.canAskNative,
    supportsFailClosed: cap.hooks.supportsFailClosed,
    oss,
    enterprise,
    routeNote: source.routeNote,
  };
}

// ---------------------------------------------------------------------------
// Features

export interface FeatureRow {
  id: string;
  label: string;
  href: string;
  group: FeatureGroup;
  oss: Record<OsId, Status>;
  enterprise: Record<OsId, Status>;
  note?: string;
}

interface FeatureSource {
  id: string;
  label: string;
  href: string;
  group: FeatureGroup;
  note?: string;
}

// Enterprise "not-offered" rows are the per-user CLI surfaces: the enterprise
// packages ship no per-user `defenseclaw` CLI, and a managed computer refuses
// per-user commands (internal/cli/managed_host_guard.go).
const featureSources: FeatureSource[] = [
  { id: 'guardrails', label: 'Guardrails: observe, action, block', href: '/docs/setup/guardrail', group: 'Protect' },
  { id: 'policy', label: 'Policy and rule packs', href: '/docs/policies', group: 'Protect' },
  {
    id: 'codeguard',
    label: 'CodeGuard',
    href: '/docs/reference/cli#scanning',
    group: 'Protect',
    note: 'Enterprise: part of the local policy engine in the standalone profile.',
  },
  { id: 'skill-scanner', label: 'Skill scanner', href: '/docs/setup/skill-scanner', group: 'Protect' },
  { id: 'mcp-scanner', label: 'MCP scanner', href: '/docs/setup/mcp-scanner', group: 'Protect' },
  {
    id: 'judge',
    label: 'LLM judge',
    href: '/docs/reference/cli#guardrail',
    group: 'Protect',
  },
  { id: 'redaction', label: 'Redaction profiles', href: '/docs/reference/redaction', group: 'Protect' },
  {
    id: 'sandboxes',
    label: 'OpenShell sandboxes',
    href: '/docs/sandboxes',
    group: 'Protect',
    note: 'Linux and macOS only. Managed installs don’t start the sandbox runtime yet.',
  },
  { id: 'acp', label: 'ACP guard (Kiro, Zed)', href: '/docs/acp-guard', group: 'Protect' },
  { id: 'ai-discovery', label: 'AI discovery', href: '/docs/ai-discovery', group: 'Discover' },
  {
    id: 'runtime-discovery',
    label: 'Runtime discovery',
    href: '/docs/ai-discovery#operator-cli',
    group: 'Discover',
  },
  { id: 'tools', label: 'Tool inventory', href: '/docs/reference/cli#asset-policy-commands', group: 'Discover' },
  { id: 'plugins', label: 'Plugin inventory and scan', href: '/docs/reference/cli#scanning', group: 'Discover' },
  { id: 'registries', label: 'Registries', href: '/docs/setup/registries', group: 'Discover' },
  { id: 'aibom', label: 'AIBOM', href: '/docs/ai-discovery#aibom-ai-bill-of-materials', group: 'Discover' },
  {
    id: 'otlp',
    label: 'OpenTelemetry export (Grafana)',
    href: '/docs/observability/grafana-dashboards',
    group: 'Observe',
  },
  { id: 'galileo', label: 'Galileo', href: '/docs/observability/galileo', group: 'Observe' },
  {
    id: 'splunk',
    label: 'Splunk',
    href: '/docs/observability/splunk',
    group: 'Observe',
    note: 'Needs a Splunk Observability Cloud organization, and Terraform for the dashboards.',
  },
  {
    id: 'local-stack',
    label: 'Local observability stack',
    href: '/docs/observability/local-observability',
    group: 'Observe',
    note: 'Needs Docker.',
  },
  { id: 'alerts', label: 'Alerts', href: '/docs/reference/cli#audit--alerts', group: 'Observe' },
  {
    id: 'webhooks',
    label: 'Webhooks',
    href: '/docs/setup/webhooks',
    group: 'Observe',
  },
  { id: 'audit', label: 'Audit log and export', href: '/docs/reference/cli#audit--alerts', group: 'Observe' },
  {
    id: 'install',
    label: 'Install',
    href: '/docs/get-started/install',
    group: 'Operate',
    note: 'Open source: the one-line installer. Enterprise: the .rpm, .pkg or Setup.exe package.',
  },
  { id: 'upgrade', label: 'Upgrade', href: '/docs/get-started/upgrade', group: 'Operate' },
  { id: 'uninstall', label: 'Uninstall', href: '/docs/reference/cli#uninstall--disable', group: 'Operate' },
  {
    id: 'health',
    label: 'Health check and repair',
    href: '/docs/reference/cli#doctor',
    group: 'Operate',
    note: 'Open source: doctor. Enterprise: verify and repair.',
  },
  {
    id: 'keys',
    label: 'Keys and secrets',
    href: '/docs/reference/keys',
    group: 'Operate',
    note: 'Enterprise: the Cisco AI Defense key is a protected credential only the gateway service can read.',
  },
  { id: 'tui', label: 'Terminal UI', href: '/docs/tui', group: 'Operate' },
  { id: 'macos-app', label: 'macOS menu-bar app', href: '/docs/macos-app', group: 'Operate' },
  {
    id: 'machine-policy',
    label: 'Machine policy for agent hooks',
    href: '/docs/enterprise/machine-policy',
    group: 'Enterprise controls',
  },
  {
    id: 'tamper',
    label: 'Tamper resistance',
    href: '/docs/enterprise/threat-model',
    group: 'Enterprise controls',
    note: 'Standard users can’t turn DefenseClaw or its hooks off.',
  },
  {
    id: 'enrollment',
    label: 'Multi-user enroll and revoke',
    href: '/docs/enterprise/enrollment',
    group: 'Enterprise controls',
  },
  {
    id: 'foreign-hook-guard',
    label: 'Foreign-hook guard',
    href: '/docs/enterprise/foreign-hook-guard',
    group: 'Enterprise controls',
  },
  {
    id: 'mdm',
    label: 'MDM deployment',
    href: '/docs/enterprise/mdm',
    group: 'Enterprise controls',
    note: 'Intune, Jamf, Kandji, Workspace ONE, ConfigMgr and Linux configuration management.',
  },
];

function buildFeature(source: FeatureSource): FeatureRow {
  const codes = generated.features[source.id];
  if (!codes) throw new Error(`support-matrix: missing feature status for ${source.id}`);
  return {
    ...source,
    oss: perOs(codes.oss, `${source.id} oss`),
    enterprise: perOs(codes.enterprise, `${source.id} enterprise`),
  };
}

export const FEATURE_GROUPS: FeatureGroup[] = ['Protect', 'Discover', 'Observe', 'Operate', 'Enterprise controls'];

export const supportMatrix = {
  asOf: generated.asOf,
  release: '1.0',
  platforms,
  connectors: connectorSources.map(buildConnector),
  features: featureSources.map(buildFeature),
};

export function connectorById(id: string): ConnectorRow | undefined {
  return supportMatrix.connectors.find((connector) => connector.id === id);
}

export const STATUS_LABEL: Record<Status, string> = {
  supported: 'Supported',
  preview: 'Preview',
  unsupported: 'Not supported',
  'not-offered': 'Not offered',
};
