// Copyright 2026 Cisco Systems, Inc. and its affiliates
// SPDX-License-Identifier: Apache-2.0
//
// Render a Policy into the multiple files the gateway expects on
// disk. This mirrors the on-disk layout in policies/ so the operator
// can paste the output directly under ~/.defenseclaw/policies/.

import yaml from 'js-yaml';
import type { Policy } from '../types';
import { projectPolicyToData } from './data-projection';

export interface EmittedFile {
  path: string;
  contents: string;
  description: string;
}

const YAML_OPTS: yaml.DumpOptions = {
  indent: 2,
  lineWidth: 100,
  noRefs: true,
  sortKeys: false,
};

function dump(value: unknown): string {
  return yaml.dump(value, YAML_OPTS);
}

export function emit(policy: Policy): EmittedFile[] {
  const files: EmittedFile[] = [];
  const packName = policy.rule_pack.name || policy.name;

  // 1) Top-level admission policy YAML.
  const policyYaml = {
    name: policy.name,
    description: policy.description,
    admission: policy.admission,
    skill_actions: policy.skill_actions,
    scanner_overrides: policy.scanner_overrides,
    first_party_allow_list: policy.first_party_allow_list,
    guardrail: {
      block_threshold: policy.guardrail.block_threshold,
      alert_threshold: policy.guardrail.alert_threshold,
      cisco_trust_level: policy.guardrail.cisco_trust_level,
      hilt: policy.guardrail.hilt,
      patterns: policy.guardrail.patterns,
      severity_mappings: policy.guardrail.severity_mappings,
    },
    firewall: policy.firewall,
    watch: policy.watch,
    enforcement: policy.enforcement,
    audit: policy.audit,
    webhooks: policy.webhooks,
    scanners: policy.scanners,
  };
  files.push({
    path: `~/.defenseclaw/policies/${policy.name}.yaml`,
    contents:
      `# DefenseClaw policy: ${policy.name}\n` +
      `# ${policy.description}\n` +
      `# Generated by docs-site policy creator. Edit by hand or regenerate.\n` +
      `# Activate with: defenseclaw policy activate ${policy.name}\n\n` +
      dump(policyYaml),
    description: 'Top-level admission/severity/firewall/audit policy YAML',
  });

  // 2) The data.json projection that OPA will read.
  const opaData = projectPolicyToData(policy);
  files.push({
    path: `~/.defenseclaw/policies/rego/data.json`,
    contents: JSON.stringify(opaData, null, 2) + '\n',
    description: 'OPA data.json — read by every Rego module at evaluation time',
  });

  // 3) Per-file rule-pack YAMLs.
  for (const rf of policy.rule_pack.files) {
    if (!rf.rules.length) continue;
    files.push({
      path: `~/.defenseclaw/policies/guardrail/${packName}/rules/${rf.filename}.yaml`,
      contents: dump({ version: 1, category: rf.category, rules: rf.rules }),
      description: `Rule pack: ${rf.filename}.yaml (${rf.rules.length} rule${rf.rules.length === 1 ? '' : 's'})`,
    });
  }

  // 4) Suppressions.
  const supp = policy.suppressions;
  if (
    supp.pre_judge_strips.length > 0 ||
    supp.finding_suppressions.length > 0 ||
    supp.tool_suppressions.length > 0
  ) {
    files.push({
      path: `~/.defenseclaw/policies/guardrail/${packName}/suppressions.yaml`,
      contents: dump({
        version: 1,
        pre_judge_strips: supp.pre_judge_strips,
        finding_suppressions: supp.finding_suppressions,
        tool_suppressions: supp.tool_suppressions,
      }),
      description: `Suppressions: ${supp.pre_judge_strips.length} pre-strip · ${supp.finding_suppressions.length} finding · ${supp.tool_suppressions.length} tool`,
    });
  }

  // 5) Sensitive tools.
  if (policy.sensitive_tools.length > 0) {
    files.push({
      path: `~/.defenseclaw/policies/guardrail/${packName}/sensitive-tools.yaml`,
      contents: dump({ version: 1, tools: policy.sensitive_tools }),
      description: `Sensitive tool inspection: ${policy.sensitive_tools.length} tool${policy.sensitive_tools.length === 1 ? '' : 's'}`,
    });
  }

  // 6) Judge configs.
  for (const judge of policy.judges) {
    if (!judge.system_prompt) continue;
    files.push({
      path: `~/.defenseclaw/policies/guardrail/${packName}/judge/${judge.name}.yaml`,
      contents: dump({
        version: 1,
        name: judge.name,
        enabled: judge.enabled,
        system_prompt: judge.system_prompt,
        ...(judge.adjudication_prompt ? { adjudication_prompt: judge.adjudication_prompt } : {}),
        ...(judge.min_categories_for_high
          ? { min_categories_for_high: judge.min_categories_for_high }
          : {}),
        ...(judge.single_category_max_severity
          ? { single_category_max_severity: judge.single_category_max_severity }
          : {}),
        categories: judge.categories,
      }),
      description: `Judge config: ${judge.name}`,
    });
  }

  // 7) Custom Rego snippets (Phase 5).
  for (const snippet of policy.custom_rego) {
    if (!snippet.source.trim()) continue;
    files.push({
      path: `~/.defenseclaw/policies/rego/custom-${snippet.name}.rego`,
      contents:
        `# ${snippet.description}\n` +
        `# Generated by docs-site policy creator. Run \`opa check\` after install.\n` +
        snippet.source.trimEnd() +
        '\n',
      description: `Custom Rego snippet: ${snippet.name}`,
    });
  }

  return files;
}
