{{- if and .Values.agentControl.enabled .Values.agentControl.postgres.enabled .Values.agentControl.postgres.persistence.enabled (not .Values.agentControl.postgres.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.agentControl.postgres.persistence.claimName | default (printf "%s-data" .Values.agentControl.postgres.name) }}
  labels:
    app.kubernetes.io/component: database
    app.kubernetes.io/name: {{ .Values.agentControl.name }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.agentControl.postgres.persistence.storageClassName }}
  storageClassName: {{ .Values.agentControl.postgres.persistence.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.agentControl.postgres.persistence.size }}
{{- end }}
