apiVersion: v1
kind: Service
metadata:
  name: {{ include "defenseclaw.fullname" . }}
  labels:
    {{- include "defenseclaw.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: api
      port: {{ .Values.service.port }}
      targetPort: api
      protocol: TCP
  selector:
    {{- include "defenseclaw.selectorLabels" . | nindent 4 }}
---
{{- if .Values.uiService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "defenseclaw.fullname" . }}-ui
  labels:
    {{- include "defenseclaw.labels" . | nindent 4 }}
    app.kubernetes.io/component: dashboard
  {{- with .Values.uiService.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.uiService.type }}
  ports:
    - name: http
      port: {{ .Values.uiService.port }}
      targetPort: api
      protocol: TCP
  selector:
    {{- include "defenseclaw.selectorLabels" . | nindent 4 }}
{{- end }}
