# Copyright 2026 Cisco Systems, Inc. and its affiliates
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0

"""Phase 7 patch: render a self-contained bash install script.

Mirrors ``docs-site/components/policy-creator/lib/emit-script.ts``.
The script is what the operator gets when they hit ``Export script``
in the modal: a single bash blob that stamps every emitted file via
heredocs and finishes with ``defenseclaw policy activate``.

The TUI's preferred path is to call ``defenseclaw policy import``
directly (Phase 13), which writes the same files in-process. The
script remains useful for share-with-coworker workflows where the
artifact has to live in a chat message, a wiki, or a config-repo
commit.
"""

from __future__ import annotations

import secrets

from defenseclaw.tui.creator.emit import EmittedFile, emit
from defenseclaw.tui.creator.types import Policy

_HEADER = """\
#!/usr/bin/env bash
# DefenseClaw policy install script - generated by the Python TUI.
# Inspect every heredoc below before running. Re-run is idempotent.
set -euo pipefail

POLICIES_ROOT="${HOME}/.defenseclaw/policies"
mkdir -p "${POLICIES_ROOT}"
"""

_FOOTER_TEMPLATE = """
# Activate the new policy.
defenseclaw policy activate {name_quoted}
echo
echo "Activated policy: {name}"
"""


def _rel_path(path: str) -> str:
    """Strip the ``~/.defenseclaw/policies/`` prefix that
    ``emit()`` produces; the bash uses ``${POLICIES_ROOT}`` instead.
    """
    prefix = "~/.defenseclaw/policies/"
    if path.startswith(prefix):
        return path[len(prefix) :]
    return path


def _shell_quote(value: str) -> str:
    """Single-quote a string for bash. Replaces embedded single
    quotes with ``'\\''`` per POSIX-shell convention so injection is
    impossible even if the operator put a quote in the policy name.
    """
    return "'" + value.replace("'", "'\\''") + "'"


def _heredoc(target: str, body: str) -> str:
    """Produce a ``mkdir -p`` + ``cat <<DELIM`` block for one file.

    The delimiter is a fresh CSPRNG-backed token so a literal
    ``DC_EOF_xxxxxx`` inside the policy contents can't terminate the
    block early. The ``'<delim>'`` quoting form prevents bash from
    expanding ``$vars`` or backticks inside the body, so embedded
    Rego or YAML stays byte-identical to what ``emit()`` produced.
    """
    delim = "DC_EOF_" + secrets.token_hex(4).upper()
    safe_target = target.replace('"', '\\"')
    body_trimmed = body.rstrip()
    return (
        f'mkdir -p "$(dirname "{safe_target}")"\n'
        f'cat > "{safe_target}" <<\'{delim}\'\n'
        f"{body_trimmed}\n"
        f"{delim}\n"
        f'echo "  wrote {safe_target}"\n'
    )


def emit_install_script(policy: Policy) -> str:
    """Return a single bash-script string ready to ``chmod +x``.

    Mirrors ``emitInstallScript`` in ``emit-script.ts``. The output
    is deliberately ASCII-only (no fancy box-drawing) so it survives
    pasting through Slack / GitHub / chat clients.
    """

    files: list[EmittedFile] = emit(policy)
    body_blocks: list[str] = []
    for f in files:
        rel = _rel_path(f.path)
        target = f"${{POLICIES_ROOT}}/{rel}"
        body_blocks.append(f"# {f.description}\n{_heredoc(target, f.contents)}")
    body = "\n".join(body_blocks)

    name_quoted = _shell_quote(policy.name)
    footer = _FOOTER_TEMPLATE.format(name_quoted=name_quoted, name=policy.name)
    return f"{_HEADER}\n{body}\n{footer}"
